


// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 16 Apr 2014 21:20:43 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.17116.0")]
[assembly: AssemblyFileVersion("1.0.17116.2120")]
