// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 22 Apr 2014 14:17:49 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.0.17122.0")]
[assembly: AssemblyFileVersion("2.0.17122.1417")]
